# Generated by Django 3.2.3 on 2024-08-18 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование категории', max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в идентификаторе!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug-имя')),
                ('image', models.ImageField(blank=True, upload_to='products/category/', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование категории', max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в идентификаторе!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug-имя')),
                ('image_size_a', models.ImageField(blank=True, upload_to='products/category/subcategory/', verbose_name='Изображение товара')),
                ('image_size_b', models.ImageField(blank=True, upload_to='products/category/subcategory/', verbose_name='Изображение товара')),
                ('image_size_c', models.ImageField(blank=True, upload_to='products/category/subcategory/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0, verbose_name='Количество')),
                ('total_coast', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Наименование подкатегории', max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в идентификаторе!', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Slug-имя')),
                ('image', models.ImageField(blank=True, upload_to='products/category/subcategory/', verbose_name='Изображение товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='products.shoppingcart')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartitem',
            constraint=models.UniqueConstraint(fields=('product', 'shopping_cart'), name='shopping_cart_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_shopping_cart'),
        ),
    ]
