# Generated by Django 3.2.3 on 2024-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_shoppingcartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
    ]
